# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODJiY2ZlMWE5YmM1ODA0MWNiZjUwNTRhMTUzZTcyZGU1ODg4NzFhZjcwMmY5YjAwZDAzNWY5ZTQ3OWJkN2MxMWYzZmFmMmJjODkzMzQxYTFmYThmYjE0MDVmNmIzNDdiZGJlMzUwYWQzZjliNDE1NmQzZDBlY2NiODY5MTgyNWU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
